import React from "react";
import styles from "./aiSummaryCard.module.scss";

interface AiSummaryCardProps {
    description: string | null;
    loading: boolean;
    failed: boolean;
    fallbackText: string;
}

const AiSummaryCard = ({ description, loading, failed, fallbackText }: AiSummaryCardProps) => {
    if (loading) {
        return (
            <div className={`${styles.aiCard} ${styles['aiCard--loading']}`}>
                <div className={styles.shimmerLine} />
                <div className={styles.shimmerLine} />
                <div className={styles.shimmerLine} />
            </div>
        );
    }

    if (description) {
        return (
            <div className={styles.aiCard}>
                <p className={styles.aiCard__description}>{description}</p>
                <p className={styles.aiCard__attribution}>
                    Description generated by OpenAI
                </p>
            </div>
        );
    }

    if (failed) {
        return (
            <div className={styles.aiCard}>
                <p className={styles.aiCard__description}>{fallbackText}</p>
            </div>
        );
    }

    return null;
};

export default AiSummaryCard;
